### ISSUE TITLE
Can't Install skorecard[dashboard]

### ISSUE THREAD

**Issue by hanhandata** [ing-bank/skorecard#111]
Hi All,

We can't install skorecard[dashboard] for interactive, do you know about this? the below is error

(base) -MacBook-Air ~ % pip3 install --upgrade skorecard[dashboard]
zsh: no matches found: skorecard[dashboard]
(base) s-MacBook-Air ~ % pip install --upgrade skorecard[dashboard] 
zsh: no matches found: skorecard[dashboard]

Thanks

**Comment by ReinierKoops** [comment]
Sorry for the inconvenience. The build process of Skorecard was updated. Will propose a fix so that it works like before.

**Comment by ReinierKoops** [comment]
This is fixed in the latest version
