### ISSUE TITLE
missing value similar

### ISSUE THREAD

**Issue by orchardbirds** [ing-bank/skorecard#13]
add option 'similar' (where the WoE of the missing buckets is the closest to the WoE of the bucket)

**Comment by orchardbirds** [comment]
@sbjelogr Do I understand this correctly?

Imagine the missings are put into their own bucket and have a WoE 0.2.
Then, look at the WoE of the other buckets. Whichever bucket has abs(WoE) closest to 0.2, add the missings to this bucket

**Comment by sbjelogr** [comment]
Well almost.

You do not really have to compute the WoE for the missing.
This imputation assumes that the WoE for missing is 0 (in other words, it adds no information), therefore the user decides to add the missing value to the bucket that is the closest to the WoE of 0.

This is mostly to be decided based on business intuition.

**Comment by orchardbirds** [comment]
But this is the logic of the 'neutral' that I just implemented :D. Unless I did the wrong logic for the other one!
