### ISSUE TITLE
Check missing value bucket assignment

### ISSUE THREAD

**Issue by timvink** [ing-bank/skorecard#14]
![image](https://user-images.githubusercontent.com/5570380/121894575-93a9ef80-cd1f-11eb-8c73-9d9848152bcd.png)

Notice missing bucket is put together with bucket 0. Let's check to make sure this is correct.

@sbjelogr Do you have the code that generated this table?

**Comment by sbjelogr** [comment]
@timvink , there you go.

```python
from skorecard import datasets
from skorecard.bucketers import OptimalBucketer, EqualFrequencyBucketer
from skorecard.pipeline import BucketingProcess
from sklearn.pipeline import make_pipeline

df = datasets.load_uci_credit_card(as_frame=True)
y = df["default"]
X = df.drop(columns=["default"])

num_cols = ["LIMIT_BAL", "BILL_AMT1"]


bucketing_process = BucketingProcess(
        prebucketing_pipeline=make_pipeline(
                EqualFrequencyBucketer(variables=num_cols, n_bins=12),
        ),
        bucketing_pipeline=make_pipeline(
                OptimalBucketer(variables=num_cols, max_n_bins=5, min_bin_size=0.1),

        ),
)

bucketing_process.fit(X,y)

bucketing_process.prebucket_table("LIMIT_BAL")
```

**Comment by timvink** [comment]
This is indeed a bug. We find the bucket by transforming the pre-bucket, but `-1` is not `NA`, leading to a different bucket.

https://github.com/ing-bank/skorecard/blob/723767a5505516da7ec997ee0364fe4053c88a7e/skorecard/pipeline/bucketing_process.py#L306-L309

Will fix.
