### ISSUE TITLE
WoeEncoder can produce wrong value

### ISSUE THREAD

**Issue by timvink** [ing-bank/skorecard#35]
I am struggling with `ValueError: Input contains NaN, infinity or a value too large for dtype('float64').` and managed to get the cause down to `WoeEncoder`. 

We should test that transformer more thoroughly.

**Comment by sbjelogr** [comment]
Do you have the code snippet and the whole error stack?

**Comment by timvink** [comment]
Went back to this, could not reproduce original error after solving #32. Quite sure that was the cause.
