### ISSUE TITLE
Make the package more visible online

### ISSUE THREAD

**Issue by Matgrb** [ing-bank/skorecard#38]
Currently it is very difficult to find this page online, you cannot find it if you google:
- skorecard
- skorecard ing bank
- skorecard github

I can only find this repo by first finding the pypi page - at the bottom :( .
![image](https://user-images.githubusercontent.com/40659437/127451649-4655c9c4-2df2-4ea0-8a6f-6b8b2cc2e12e.png)

It might be issue with indexing in google that it takes some time for them to index it, but i think the visibility of this package can be improved, by:
- modifying text of the page to include more of the relevant keywords that would be picked up by google
- Adding more links between pages e.g. docs -> github, github -> docs, but also other websites pointing to this repo
- writing a blogpost about it :)

**Comment by timvink** [comment]
Situation is not as bad for me though. But `scorecard python` should have `skorecard` on the first page preferately. Good tips!

![image](https://user-images.githubusercontent.com/5570380/127453297-16367e98-daf2-43c5-9403-315d14bad7e1.png)

**Comment by Matgrb** [comment]
Indeed when i have opened an incognito page it looks much better. I am wondering why it didn't show up similarly for my personal account, probably many users would have a similar issue.

**Comment by timvink** [comment]
Had a look at this again. Links between github and docs are there, as well as keywords mentioned. Writing a blog would be nice & is on my wishlist, but doesn't merit an open issue. Closing :)
