### ISSUE TITLE
Improve training time performance of Skorecard()

### ISSUE THREAD

**Issue by timvink** [ing-bank/skorecard#48]
If you look at the [benchmarks](https://ing-bank.github.io/skorecard/discussion/benchmarks/), the training time of `Skorecard` is quite terrible:

![image](https://user-images.githubusercontent.com/5570380/130629047-91576bfb-5620-4c74-a058-6d5ad3c37d47.png)

We would have to profile it, but I suspect there are two main reasons:

1) `skorecard/linear_model/linear_model.py` always calculating & saving the covariance matrix
2) detecting numerical and categorical columns in `_setup` , for example this line:
https://github.com/ing-bank/skorecard/blob/ccd6f0cca83326811bbaa933516de043c8622edf/skorecard/skorecard.py#L227

For 1), we might add a flag to be able to turn this off? Especially when grid searching or doing some CV benchmarks, these statistics are unnecessary to calculate.
For 2) we might find better tricks and defaults

**Comment by orchardbirds** [comment]
@timvink You say fix available, did you improve the benchmarks then? If so, can we close this?

**Comment by timvink** [comment]
Yes, it's now slightly improved: 

![image](https://user-images.githubusercontent.com/5570380/132324473-3cf344c8-00bd-4224-aa8b-1bf23cdc343f.png)
