### ISSUE TITLE
Add Weight Plot

### ISSUE THREAD

**Issue by orchardbirds** [ing-bank/skorecard#58]
From Satya:

"Also a suggestion, the coefficients have their own intervals(usually 5% and 95%), it would be great to have a weight plot. I would like to contribute in this issue."

**Comment by orchardbirds** [comment]
@satya-pattnaik it would be great to have documentation for this, too.

**Comment by orchardbirds** [comment]
It seems I cannot assign you, are you able to assign yourself, @satya-pattnaik ? :)

**Comment by satya-pattnaik** [comment]
No even I am not able to assign it to myself.

**Comment by orchardbirds** [comment]
OK, I think you can still make a PR though, so I would just say go for it! :)

**Comment by satya-pattnaik** [comment]
Sure!
