### ISSUE TITLE
add feature selection method

### ISSUE THREAD

**Issue by JYLFamily** [ing-bank/skorecard#71]
Hi skorecad team:
    1.How to deal with logistic regression regression feature coefficient is positive(features are transformed by woe)?
    2.What is a good way to select scorecard feature to ensure that all feature coefficients are positive?
thanks

**Comment by anilkumarpanda** [comment]
Hi @JYLFamily thanks for the questions .
1.  For the first question ,can you please elaborate on your question ?
2. For the second one, I don't think there is an automated way to select features such that coefficients are positive . However you can have a robust feature selection process that ensure that you do not have features with high correlation both univariate and multivariate.
Despite that sometimes you can end up in a scenario that a feature when used individually produces a positive co-efficient, however when used in a multi-variate setting, leads to a negative co-efficient. That can lead to interpretability issues. One option is to drop those feature/s manually. Generally those are less important features.

**Comment by anilkumarpanda** [comment]
@JYLFamily we believe this covered by recent commit, hence this issue can be closed. I you have further question please reopen the issue.
