### ISSUE TITLE
Skorecard() class is slow

### ISSUE THREAD

**Issue by orchardbirds** [ing-bank/skorecard#74]
From the benchmarks notebook, Skorecard is now 'very' slow:

![Screenshot 2021-11-22 at 13 07 15](https://user-images.githubusercontent.com/49144672/142859305-02a39c29-0ea8-43ea-8f4c-d125cc940d58.png)

**Comment by dlaprins** [comment]
It seems to me that part of the reason for the speed issue is that the fit of the BucketingProcess class calculates bucket_tables and summaries both in the call to the fit of the underlying (pre-)bucketers, and in the BucketingProcess fit itself.

I have added a get_statistics Boolean to the bucketers which can be used to turn off the calculation of the bucket tables and summary in the bucketers. Making use of this feature in a BucketingProcess results in no loss of functionality, but does result in a minor speed increase. A notebook benchmark_stats_feature in docs/discussion compares running Skorecard with and without the bucketer statistics.

**Comment by timvink** [comment]
Thanks @dlaprins .

We could probably optimize the speed further, let's do that in separate issues should the need arise.
