### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by dlaprins** [ing-bank/skorecard#94]
Skorecard relies on the optbinning package, but optbinning is not in the base_packages list of setup.py. It should be.

**Comment by timvink** [comment]
The idea initially was that you can use `skorecard` without `optbinning` also, which is quite a heavy depencency.

Hence this code, which gives a helpful error message:

https://github.com/ing-bank/skorecard/blob/bf6a89e4b0fc23ab97bdf587c851d2eb244a759f/skorecard/bucketers/bucketers.py#L19-L22

But now `bucketers.py` has a lot more bucketers than just `OptimalBucketer`, so you can't really get around it. So, either we add it as a dependency, or, we separate each bucketer into it's own module (and use the `__init__.py`  file to control the namespace, so we don't breaking any existing imports).

**Comment by Dronakurl** [comment]
When we still want to be able to use skorecard without the package:
Couldn't we do the following?
- put the `OptimalBucketer` class in a separate file within the `bucketers` folder
- adjust `bucketers/__init__.py, that it imports `OptimalBucketer` only if optbinning is installed
So if someone uses `import bucketers` nothing is broken and `from bucketers import OptimalBucketer` should still work
